#=================================基础配置========================================================
server:
  port: 8088
spring:
  cloud:
    client:
      ipAddress: 127.0.0.1
  application:
    name: springboot2-quartz-demo
#=================================数据库配置========================================================
  datasource:
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    schema: classpath:schema-quartz.sql
    minIdle: 5
    validationQuery: select 'x'
    initialSize: 5
    maxWait: 60000
    poolPreparedStatements: true
    filters: stat,wall,slf4j
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost/quartz?useUnicode=true&characterEncoding=utf-8&useSSL=false&useAffectedRows=true&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    platform: mysql
    maxPoolPreparedStatementPerConnectionSize: 20
    testOnBorrow: false
    testWhileIdle: true
    minEvictableIdleTimeMillis: 30000
    timeBetweenEvictionRunsMillis: 60000
    testOnReturn: false
    driver-class-name: com.mysql.cj.jdbc.Driver
    maxActive: 300
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
#=================================其他配置========================================================
#解决mybaits传入空值问题
mybatis:
  configuration:
    jdbc-type-for-null: NULL
    map-underscore-to-camel-case: true
#配置swagger
swagger:
  basePackage: com.beyondli.controller
  description: springboot2-quartz-demo
  title: springboot2-quartz-demo
  version: V1.0
  enable: true
